// Generated by CoffeeScript 2.4.1
(function() {
  window.NodeNotify = class NodeNotify {
    constructor(server) {
      var head, script;
      this.sub = this.sub.bind(this);
      this.server = server;
      this.subs = {};
      if (!window.io) {
        head = document.getElementsByTagName('head')[0];
        script = document.createElement('script');
        script.src = `${this.server}/socket.io/socket.io.js`;
        head.appendChild(script);
      }
    }

    sub(name, func) {
      return this.subs[name] = (data) => {
        if (!this.socket) {
          return;
        }
        return func(data);
      };
    }

    connect(func) {
      var channel, url;
      channel = func();
      if (channel && window.io) {
        url = `${this.server}/c/${channel}`;
        this.socket = io.connect(url);
        return this.socket.on('msg', (response) => {
          var c;
          if (c = this.subs[response.func]) {
            return c(response.data);
          }
        });
      } else {
        return setTimeout(() => {
          return this.connect(func);
        }, 200);
      }
    }

  };

}).call(this);
